config/routes.rb
Csilk::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  get "welcome/index"

  scope '/admin' do
    root :to => 'admin/dashboard#index'
    #devise_for :users, :as => :admin#, :controllers => { :sessions => 'admin/sessions', :passwords => 'admin/passwords' }
    devise_for :users, :path_names => {
      :sign_in => '',
      :sign_out => 'logout',
      :password => 'secret',
      :confirmation => 'verification',
      :unlock => 'unblock',
      :registration => 'register',
      :sign_up => 'cmon_let_me_in'
    },
    :controllers => {
      :sessions  => 'admin/sessions',
      :passwords => 'admin/passwords',
      #:registration => 'admin/users/register/cmon_let_me_in',
      #:sign_up => 'admin/novo'
    }
  end

  # INSTITUCIONAL
  get '/quem-somos' => 'welcome#quem_somos', :as => "quem_somos"
  get '/o-que-fazemos' => 'welcome#fazemos', :as => "fazemos"
  get '/clientes' => 'welcome#clientes', :as => "clientes"
  get '/sustentabilidade' => 'welcome#sustentabilidade', :as => "sustentabilidade"
  get '/projeto-social' => 'welcome#social', :as => "social"

  # CATEGORIAS
  get '/produtos/' => 'categoria#index', :as => "produtos"
  get '/produtos/:categoria' => 'categoria#show', :as => "categoria"
  
  # PRODUTOS
  get '/produtos/:categoria/:produto' => 'produtos#index', :as => "produto"
  get '/produtos/:categoria/:produto/salvar-contato' => 'produtos#contato', :as => 'contato_produtos'
  get '/produtos/:categoria/:produto/visita' => 'produtos#aumenta_visita', :as => 'visita_produtos'

  # CONTATO
  get '/contato' => 'contato#new', :as => "contatos"
  post '/contato' => 'contato#create'

  # CONTATO
  get '/cotacao' => 'cotacao#new', :as => "cotacoes"
  post '/cotacao' => 'cotacao#create'

  # SEJA UM FORNECEDOR
  get '/seja-um-fornecedor' => 'fornecedor#new', :as => "fornecedores"
  post '/seja-um-fornecedor' => 'fornecedor#create'

  # NEWSLETTER
  get '/newsletter' => 'newsletter#novo', :as => "newsletters"

  namespace :admin do
    # colocar todos os resources aqui
    resources :categorias
    resources :banners
    resources :newsletters
    resources :contatos
    resources :fornecedores
    resources :produtos
    resources :fotos
    resources :contato_produtos
    resources :cotacoes

    controller :banners do
      put "banners/:id/desativar", :action => :desativar
      put "banners/:id/ativar", :action => :ativar
    end
  end

  root :to => 'welcome#index'
end

app/controllers/admin/fornecedores_controller.rb
class Admin::FornecedoresController < Admin::AdminController
layout 'admin'  
before_filter :authenticate_user!
  # GET /fornecedores
  # GET /fornecedores.json
  def index
    @fornecedores = Fornecedor.all.sort! { |a,b| b.id <=> a.id }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fornecedores }
    end
  end

  # GET /fornecedores/1
  # GET /fornecedores/1.json
  def show
    @fornecedor = Fornecedor.find(params[:id])
    @fornecedor.update_attributes(:novo => 0 )

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fornecedor }
    end
  end

  # GET /fornecedores/new
  # GET /fornecedores/new.json
  def new
    @fornecedor = Fornecedor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fornecedor }
    end
  end

  # GET /fornecedores/1/edit
  def edit
    @fornecedor = Fornecedor.find(params[:id])
  end

  # POST /fornecedores
  # POST /fornecedores.json
  def create
    @fornecedor = Fornecedor.new(params[:fornecedor])

    respond_to do |format|
      if @fornecedor.save
        format.html { redirect_to [:admin, @fornecedor], notice: 'Fornecedor was successfully created.' }
        format.json { render json: @fornecedor, status: :created, location: @fornecedor }
      else
        format.html { render action: "new" }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fornecedores/1
  # PUT /fornecedores/1.json
  def update
    @fornecedor = Fornecedor.find(params[:id])

    respond_to do |format|
      if @fornecedor.update_attributes(params[:fornecedor])
        format.html { redirect_to [:admin, @fornecedor], notice: 'Fornecedor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedores/1
  # DELETE /fornecedores/1.json
  def destroy
    @fornecedor = Fornecedor.find(params[:id])
    @fornecedor.destroy

    respond_to do |format|
      format.html { redirect_to admin_fornecedores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fornecedores_helper.rb
module FornecedoresHelper
end

app/views/admin/fornecedores/_form.html.erb
<%= form_for [:admin, @fornecedor] do |f| %>
  <% if @fornecedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fornecedor.errors.count, "error") %> prohibited this fornecedor from being saved:</h2>

      <ul>
      <% @fornecedor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :razao_social %><br />
    <%= f.text_field :razao_social %>
  </div>
  <div class="field">
    <%= f.label :nome_fantasia %><br />
    <%= f.text_field :nome_fantasia %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br />
    <%= f.text_field :cnpj %>
  </div>
  <div class="field">
    <%= f.label :nome_contato %><br />
    <%= f.text_field :nome_contato %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :celular %><br />
    <%= f.text_field :celular %>
  </div>
  <div class="field">
    <%= f.label :fax %><br />
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :site %><br />
    <%= f.text_field :site %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cidade %><br />
    <%= f.text_field :cidade %>
  </div>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.text_field :estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/fornecedores/edit.html.erb
<h1>Editar fornecedor</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', [:admin, @fornecedor] %> |
<%= link_to 'Voltar', admin_fornecedores_path %>

app/views/admin/fornecedores/index.html.erb
<h1>Lista de fornecedores</h1>

<div id="guardaListagens">
    <table>
        <tr id="firstTr">
            <th>Razão social ou Nome fantasia</th>
            <!-- <th>CNPJ</th> -->
            <th>Nome contato</th>
            <th>Telefone</th>
            <th style="width:17%;"></th>
            <th style="width:16%;"></th>
        </tr>

        <% @fornecedores.each do |fornecedor| %>
            <% if fornecedor == @fornecedores.last && fornecedor.novo? %>
            <tr class="ultimaTr novoItemContato">
            <% elsif fornecedor == @fornecedores.last %>
            <tr class="ultimaTr">
            <% elsif fornecedor.novo? %>
            <tr class="novoItemContato">
            <% else %>
            <tr>
            <% end %>
                <td><%= fornecedor.razao_social %></td>
                <!-- <td><%#= fornecedor.cnpj %></td> -->
                <td><%= fornecedor.nome_contato %></td>
                <td><%= fornecedor.telefone %></td>
                <td><%= link_to 'Mostrar', [:admin, fornecedor] %></td>
                <td><%= link_to 'Deletar', [:admin, fornecedor], confirm: 'Tem certeza que deseja excluir este fornecedor?', method: :delete, :class => 'deletar' %></td>
            </tr>
        <% end %>
    </table>

    <br />

    <%#= link_to 'Novo Fornecedor', new_admin_fornecedor_path, :id => 'novoItem' %>
</div>

app/views/admin/fornecedores/new.html.erb
<h1>Novo fornecedor</h1>

<%= render 'form' %>

<%= link_to 'Voltar', admin_fornecedores_path %>

app/views/admin/fornecedores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Razão social ou Nome fantasia:</b>
  <%= @fornecedor.razao_social %>
</p>

<p>
  <b>CNPJ:</b>
  <%= @fornecedor.cnpj %>
</p>

<p>
  <b>Nome contato:</b>
  <%= @fornecedor.nome_contato %>
</p>

<p>
  <b>Telefone:</b>
  <%= @fornecedor.telefone %>
</p>

<p>
  <b>E-mail:</b>
  <%= @fornecedor.email %>
</p>

<%= link_to 'Voltar', admin_fornecedores_path %>