config/routes.rb
Csilk::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  get "welcome/index"

  scope '/admin' do
    root :to => 'admin/dashboard#index'
    #devise_for :users, :as => :admin#, :controllers => { :sessions => 'admin/sessions', :passwords => 'admin/passwords' }
    devise_for :users, :path_names => {
      :sign_in => '',
      :sign_out => 'logout',
      :password => 'secret',
      :confirmation => 'verification',
      :unlock => 'unblock',
      :registration => 'register',
      :sign_up => 'cmon_let_me_in'
    },
    :controllers => {
      :sessions  => 'admin/sessions',
      :passwords => 'admin/passwords',
      #:registration => 'admin/users/register/cmon_let_me_in',
      #:sign_up => 'admin/novo'
    }
  end

  # INSTITUCIONAL
  get '/quem-somos' => 'welcome#quem_somos', :as => "quem_somos"
  get '/o-que-fazemos' => 'welcome#fazemos', :as => "fazemos"
  get '/clientes' => 'welcome#clientes', :as => "clientes"
  get '/sustentabilidade' => 'welcome#sustentabilidade', :as => "sustentabilidade"
  get '/projeto-social' => 'welcome#social', :as => "social"

  # CATEGORIAS
  get '/produtos/' => 'categoria#index', :as => "produtos"
  get '/produtos/:categoria' => 'categoria#show', :as => "categoria"
  
  # PRODUTOS
  get '/produtos/:categoria/:produto' => 'produtos#index', :as => "produto"
  get '/produtos/:categoria/:produto/salvar-contato' => 'produtos#contato', :as => 'contato_produtos'
  get '/produtos/:categoria/:produto/visita' => 'produtos#aumenta_visita', :as => 'visita_produtos'

  # CONTATO
  get '/contato' => 'contato#new', :as => "contatos"
  post '/contato' => 'contato#create'

  # CONTATO
  get '/cotacao' => 'cotacao#new', :as => "cotacoes"
  post '/cotacao' => 'cotacao#create'

  # SEJA UM FORNECEDOR
  get '/seja-um-fornecedor' => 'fornecedor#new', :as => "fornecedores"
  post '/seja-um-fornecedor' => 'fornecedor#create'

  # NEWSLETTER
  get '/newsletter' => 'newsletter#novo', :as => "newsletters"

  namespace :admin do
    # colocar todos os resources aqui
    resources :categorias
    resources :banners
    resources :newsletters
    resources :contatos
    resources :fornecedores
    resources :produtos
    resources :fotos
    resources :contato_produtos
    resources :cotacoes

    controller :banners do
      put "banners/:id/desativar", :action => :desativar
      put "banners/:id/ativar", :action => :ativar
    end
  end

  root :to => 'welcome#index'
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  belongs_to :categoria
  has_many :fotos
  has_many :cotacoes

  # VALIDACOES
  validates_presence_of :nome
  validates_presence_of :slug
  validates_presence_of :categoria_id
  #validates_associated :categoria_id
  validates_uniqueness_of :nome
  validates_uniqueness_of :slug
end

app/controllers/admin/produtos_controller.rb
class Admin::ProdutosController < Admin::AdminController
layout 'admin'  
before_filter :authenticate_user!

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.order('id DESC').paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produtos }
    end
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
    @produto = Produto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/new
  # GET /produtos/new.json
  def new
    @produto = Produto.new
    @categoria_para_select = Categoria.order(:nome)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/1/edit
  def edit
    @produto = Produto.find(params[:id])
    @categoria_para_select = Categoria.order(:nome)
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(params[:produto])
    @categoria_para_select = Categoria.order(:nome)

    #def mark_for_destruction?
      #@marked_for_destruction
    #end

    respond_to do |format|
        if @produto.save
          format.html { redirect_to [:admin, @produto], notice: 'Produto criado com sucesso.' }
          format.json { render json: @produto, status: :created, location: @produto }
        else
          format.html { render action: "new" }
          format.json { render json: @produto.errors, status: :unprocessable_entity }
        end
    end
  end

  # PUT /produtos/1
  # PUT /produtos/1.json
  def update
    @produto = Produto.find(params[:id])
    @categoria_para_select = Categoria.order(:nome)

    #def mark_for_destruction?
      #@marked_for_destruction
    #end

    respond_to do |format|
      if @produto.update_attributes(params[:produto])
        format.html { redirect_to [:admin, @produto], notice: 'Produto atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to admin_produtos_url }
      format.json { head :no_content }
    end
  end

  def adicionar_fotos
    
  end

  
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  layout false, :only => [:contato]

  def index
    @produto = Produto.find_by_slug(params[:produto])
  end

  def contato
  	@contato_produto = ContatoProduto.new(params[:contato_produto])

    @produto = Produto.find(params[:produto_id])
    ncontatos = @produto.ncontatos ||= 0
    ncontatos += 1

    if @contato_produto.save && @produto.update_attributes(:ncontatos => ncontatos)
  	  @mensagem = "Mensagem enviada com sucesso."
  	else
  	  @mensagem = "Erro ao enviar mensagem."
  	end
  end
  
  def aumenta_visita
    @produto = Produto.find_by_slug(params[:produto])
    nvisitas = @produto.nvisitas ||= 0
    nvisitas += 1
    @produto.update_attribute(:nvisitas, nvisitas)
  end

end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/admin/produtos/_form.html.erb
<%= form_for [:admin, @produto] do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome, :class => 'viraSlug' %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug, :class => 'slugTransformado' %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.cktext_area :descricao, :ckeditor => {:toolbar => "Basic"} %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br />
    <%= f.collection_select :categoria_id, @categoria_para_select, :id, :nome, {:prompt => 'Selecione uma categoria' } %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <%= f.hidden_field :nvisitas, :value => @produto.nvisitas ||= 0 %>
  <%= f.hidden_field :ncontatos, :value => @produto.ncontatos ||= 0 %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/produtos/adicionar_fotos.html.erb
<h1>Adicionar fotos produtos</h1>

app/views/admin/produtos/edit.html.erb
<h1>Editar produto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', [:admin, @produto] %> |
<%= link_to 'Voltar', admin_produtos_path %>

app/views/admin/produtos/index.html.erb
<h1>Lista de produtos</h1>
<div id="guardaListagens">
    <table>
        <tr id="firstTr">
            <th style="width:10%;">Número</th>
            <th>Nome</th>
            <!-- <th>Slug</th> -->
            <!-- <th>Descricao</th> -->
            <!-- <th>Numero de visitas</th> -->
            <!-- <th>Numero de contatos</th> -->
            <th>Categoria</th>
            <th style="width:17%;"></th>
            <th style="width:17%;"></th>
            <th style="width:16%;"></th>
        </tr>

        <% @produtos.each do |produto| %>
            <% if produto == @produtos.last %>
            <tr class="ultimaTr">
            <% else %>
            <tr>
            <% end %>
                <td style="width:10%;"><%= produto.id %></td>
                <td><%= produto.nome %></td>
                <!-- <td><%= produto.slug %></td> -->
                <!-- <td><%= produto.descricao.html_safe %></td> -->
                <!-- <td><%= produto.nvisitas %></td> -->
                <!-- <td><%= produto.ncontatos %></td> -->
                <td><%= produto.categoria.nome %></td>
                <td style="width:17%;"><%= link_to 'Mostrar', [:admin, produto] %></td>
                <td style="width:17%;"><%= link_to 'Editar', edit_admin_produto_path(produto) %></td>
                <td style="width:16%;"><%= link_to "Deletar", [:admin, produto], confirm: 'Tem certeza que deseja excluir este produto?', method: :delete, :class => 'deletar' %></td>
            </tr>
        <% end %>
    </table>

    <%= will_paginate @produtos %>

    <br />

    <%= link_to 'Novo Produto', new_admin_produto_path, :id => 'novoItem' %>
</div>

app/views/admin/produtos/new.html.erb
<h1>Novo produto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', admin_produtos_path %>

app/views/admin/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Número:</b>
  <%= @produto.id %>
</p>

<p>
  <b>Nome:</b>
  <%= @produto.nome %>
</p>

<p>
  <b>Slug:</b>
  <%= @produto.slug %>
</p>

<p>
  <b>Descricao:</b>
  <%= @produto.descricao.html_safe %>
</p>

<p>
  <b>Número de visitas:</b>
  <%= @produto.nvisitas %>
</p>

<p>
  <b>Número de contatos:</b>
  <%= @produto.ncontatos %>
</p>

<p>
  <b>Categoria:</b>
  <%= @produto.categoria.nome %>
</p>

<p>
  <b>Keywords:</b>
  <%= @produto.keywords %>
</p>

<p>
  <b>Description:</b>
  <%= @produto.description %>
</p>

<p>
  <b>Fotos:</b>
</p>
<ul>
  <% @produto.fotos.each do |u| %>
    <li>
      <%= image_tag u.picture.url(:medio)%>
      <%= link_to 'Editar', edit_admin_foto_path(u) %>
      <%= link_to 'Deletar', [:admin, u], confirm: 'Tem certeza que deseja excluir esta foto?', method: :delete %>
    </li>
  <% end %>
</ul>
<%= link_to 'Nova foto', new_admin_foto_path(:produto_id => @produto.id) %>

<%= link_to 'Editar', edit_admin_produto_path(@produto) %> |
<%= link_to 'Voltar', admin_produtos_path %>