config/routes.rb
Csilk::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  get "welcome/index"

  scope '/admin' do
    root :to => 'admin/dashboard#index'
    #devise_for :users, :as => :admin#, :controllers => { :sessions => 'admin/sessions', :passwords => 'admin/passwords' }
    devise_for :users, :path_names => {
      :sign_in => '',
      :sign_out => 'logout',
      :password => 'secret',
      :confirmation => 'verification',
      :unlock => 'unblock',
      :registration => 'register',
      :sign_up => 'cmon_let_me_in'
    },
    :controllers => {
      :sessions  => 'admin/sessions',
      :passwords => 'admin/passwords',
      #:registration => 'admin/users/register/cmon_let_me_in',
      #:sign_up => 'admin/novo'
    }
  end

  # INSTITUCIONAL
  get '/quem-somos' => 'welcome#quem_somos', :as => "quem_somos"
  get '/o-que-fazemos' => 'welcome#fazemos', :as => "fazemos"
  get '/clientes' => 'welcome#clientes', :as => "clientes"
  get '/sustentabilidade' => 'welcome#sustentabilidade', :as => "sustentabilidade"
  get '/projeto-social' => 'welcome#social', :as => "social"

  # CATEGORIAS
  get '/produtos/' => 'categoria#index', :as => "produtos"
  get '/produtos/:categoria' => 'categoria#show', :as => "categoria"
  
  # PRODUTOS
  get '/produtos/:categoria/:produto' => 'produtos#index', :as => "produto"
  get '/produtos/:categoria/:produto/salvar-contato' => 'produtos#contato', :as => 'contato_produtos'
  get '/produtos/:categoria/:produto/visita' => 'produtos#aumenta_visita', :as => 'visita_produtos'

  # CONTATO
  get '/contato' => 'contato#new', :as => "contatos"
  post '/contato' => 'contato#create'

  # CONTATO
  get '/cotacao' => 'cotacao#new', :as => "cotacoes"
  post '/cotacao' => 'cotacao#create'

  # SEJA UM FORNECEDOR
  get '/seja-um-fornecedor' => 'fornecedor#new', :as => "fornecedores"
  post '/seja-um-fornecedor' => 'fornecedor#create'

  # NEWSLETTER
  get '/newsletter' => 'newsletter#novo', :as => "newsletters"

  namespace :admin do
    # colocar todos os resources aqui
    resources :categorias
    resources :banners
    resources :newsletters
    resources :contatos
    resources :fornecedores
    resources :produtos
    resources :fotos
    resources :contato_produtos
    resources :cotacoes

    controller :banners do
      put "banners/:id/desativar", :action => :desativar
      put "banners/:id/ativar", :action => :ativar
    end
  end

  root :to => 'welcome#index'
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  validates_presence_of :nome
  validates_presence_of :email
end

app/controllers/admin/newsletters_controller.rb
class Admin::NewslettersController < Admin::AdminController
layout 'admin'  
before_filter :authenticate_user!
  # GET /newsletters
  # GET /newsletters.json
  def index
    @newsletters = Newsletter.all.sort! { |a,b| b.id <=> a.id }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @newsletters }
    end
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @newsletter }
    end
  end

  # GET /newsletters/new
  # GET /newsletters/new.json
  def new
    @newsletter = Newsletter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @newsletter }
    end
  end

  # GET /newsletters/1/edit
  def edit
    @newsletter = Newsletter.find(params[:id])
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(params[:newsletter])

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to [:admin, @newsletter], notice: 'Newsletter was successfully created.' }
        format.json { render json: @newsletter, status: :created, location: @newsletter }
      else
        format.html { render action: "new" }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /newsletters/1
  # PUT /newsletters/1.json
  def update
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      if @newsletter.update_attributes(params[:newsletter])
        format.html { redirect_to [:admin, @newsletter], notice: 'Newsletter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter = Newsletter.find(params[:id])
    @newsletter.destroy

    respond_to do |format|
      format.html { redirect_to admin_newsletters_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/newsletter_controller.rb
class NewsletterController < ApplicationController
	layout false
	def novo
		@newsletter = Newsletter.new(params[:newsletter])
		if @newsletter.save
			@mensagem = "Cadastro efetuado com sucesso."
		else
			@mensagem = "Erro ao efetuar cadastro."
		end
	end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/admin/newsletters/_form.html.erb
<%= form_for [:admin, @newsletter] do |f| %>
  <% if @newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
      <% @newsletter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/newsletters/edit.html.erb
<h1>Editar newsletter</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', [:admin, @newsletter] %> |
<%= link_to 'Voltar', admin_newsletters_path %>

app/views/admin/newsletters/index.html.erb
<h1>Lista de newsletters</h1>
<div id="guardaListagens">
    <table>
        <tr id="firstTr">
            <th style="width:35%;">Nome</th>
            <th style="width:35%;">Email</th>
            <th style="width:15%;"></th>
            <th style="width:15%;"></th>
        </tr>

        <% @newsletters.each do |newsletter| %>
            <% if newsletter == @newsletters.last %>
            <tr class="ultimaTr">
            <% else %>
            <tr>
            <% end %>
                <td style="width:35%;"><%= newsletter.nome %></td>
                <td style="width:35%;"><%= newsletter.email %></td>
                <td style="width:15%;"><%= link_to 'Mostrar', [:admin, newsletter] %></td>
                <td style="width:15%;"><%= link_to 'Deletar', [:admin, newsletter], confirm: 'Tem certeza que deseja excluir este assinante?', method: :delete, :class => 'deletar' %></td>                
            </tr>
        <% end %>
    </table>

    <br />

    <%#= link_to 'Novo Newsletter', new_admin_newsletter_path, :id => "novoItem" %>
</div>

app/views/admin/newsletters/new.html.erb
<h1>Novo newsletter</h1>

<%= render 'form' %>

<%= link_to 'Voltar', admin_newsletters_path %>

app/views/admin/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @newsletter.nome %>
</p>

<p>
  <b>Email:</b>
  <%= @newsletter.email %>
</p>


<%= link_to 'Editar', edit_admin_newsletter_path(@newsletter) %> |
<%= link_to 'Voltar', admin_newsletters_path %>