config/routes.rb
Csilk::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  get "welcome/index"

  scope '/admin' do
    root :to => 'admin/dashboard#index'
    #devise_for :users, :as => :admin#, :controllers => { :sessions => 'admin/sessions', :passwords => 'admin/passwords' }
    devise_for :users, :path_names => {
      :sign_in => '',
      :sign_out => 'logout',
      :password => 'secret',
      :confirmation => 'verification',
      :unlock => 'unblock',
      :registration => 'register',
      :sign_up => 'cmon_let_me_in'
    },
    :controllers => {
      :sessions  => 'admin/sessions',
      :passwords => 'admin/passwords',
      #:registration => 'admin/users/register/cmon_let_me_in',
      #:sign_up => 'admin/novo'
    }
  end

  # INSTITUCIONAL
  get '/quem-somos' => 'welcome#quem_somos', :as => "quem_somos"
  get '/o-que-fazemos' => 'welcome#fazemos', :as => "fazemos"
  get '/clientes' => 'welcome#clientes', :as => "clientes"
  get '/sustentabilidade' => 'welcome#sustentabilidade', :as => "sustentabilidade"
  get '/projeto-social' => 'welcome#social', :as => "social"

  # CATEGORIAS
  get '/produtos/' => 'categoria#index', :as => "produtos"
  get '/produtos/:categoria' => 'categoria#show', :as => "categoria"
  
  # PRODUTOS
  get '/produtos/:categoria/:produto' => 'produtos#index', :as => "produto"
  get '/produtos/:categoria/:produto/salvar-contato' => 'produtos#contato', :as => 'contato_produtos'
  get '/produtos/:categoria/:produto/visita' => 'produtos#aumenta_visita', :as => 'visita_produtos'

  # CONTATO
  get '/contato' => 'contato#new', :as => "contatos"
  post '/contato' => 'contato#create'

  # CONTATO
  get '/cotacao' => 'cotacao#new', :as => "cotacoes"
  post '/cotacao' => 'cotacao#create'

  # SEJA UM FORNECEDOR
  get '/seja-um-fornecedor' => 'fornecedor#new', :as => "fornecedores"
  post '/seja-um-fornecedor' => 'fornecedor#create'

  # NEWSLETTER
  get '/newsletter' => 'newsletter#novo', :as => "newsletters"

  namespace :admin do
    # colocar todos os resources aqui
    resources :categorias
    resources :banners
    resources :newsletters
    resources :contatos
    resources :fornecedores
    resources :produtos
    resources :fotos
    resources :contato_produtos
    resources :cotacoes

    controller :banners do
      put "banners/:id/desativar", :action => :desativar
      put "banners/:id/ativar", :action => :ativar
    end
  end

  root :to => 'welcome#index'
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_many :produtos

  # VALIDACOES
  validates_presence_of :nome
  validates_presence_of :slug
  validates_uniqueness_of :nome
  validates_uniqueness_of :slug

  def self.com_produtos
    self.all.select {|category| category.produtos.any? }
  end

end

app/controllers/admin/categorias_controller.rb
class Admin::CategoriasController < Admin::AdminController
layout 'admin'  
before_filter :authenticate_user!

  # GET /categorias
  # GET /categorias.json
  def index
    @categorias = Categoria.order('id DESC').paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categorias }
    end
  end

  # GET /categorias/1
  # GET /categorias/1.json
  def show
    @categoria = Categoria.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @categoria }
    end
  end

  # GET /categorias/new
  # GET /categorias/new.json
  def new
    @categoria = Categoria.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @categoria }
    end
  end

  # GET /categorias/1/edit
  def edit
    @categoria = Categoria.find(params[:id])
  end

  # POST /categorias
  # POST /categorias.json
  def create
    @categoria = Categoria.new(params[:categoria])

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to [:admin, @categoria], notice: 'Categoria criada com sucesso.' }
        format.json { render json: @categoria, status: :created, location: @categoria }
      else
        format.html { render action: "new" }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categorias/1
  # PUT /categorias/1.json
  def update
    @categoria = Categoria.find(params[:id])

    respond_to do |format|
      if @categoria.update_attributes(params[:categoria])
        format.html { redirect_to [:admin, @categoria], notice: 'Categoria atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1
  # DELETE /categorias/1.json
  def destroy
    @categoria = Categoria.find(params[:id])
    @categoria.destroy

    respond_to do |format|
      format.html { redirect_to admin_categorias_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
	def index
		@categoria = Categoria.all
		#@produtos = @categoria.produtos
	end

	def show
		@categoria = Categoria.find_by_slug(params[:categoria])
		@produtos = @categoria.produtos
	end
end

app/helpers/categoria_helper.rb
# encoding:UTF-8
module CategoriaHelper
	def desc(object)
		no_html = strip_tags(object.descricao).sub("&nbsp;", "").sub("&aacute;", "á").sub("&acirc;", "â").sub("&atilde;", "ã").sub("&eacute;", "é").sub("&ecirc;", "ê").sub("&iacute;", "í").sub("&oacute;", "ó").sub("&ocirc;", "ô").sub("&uacute;", "ú").sub("&ucirc;", "û").sub("&ccedil;", "ç")
		truncate( no_html , :length => 50 )
	end
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/views/admin/categorias/_form.html.erb
<%= form_for [:admin, @categoria] do |f| %>
  <% if @categoria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categoria.errors.count, "error") %> prohibited this categoria from being saved:</h2>

      <ul>
      <% @categoria.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome, :class => 'viraSlug' %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug, :class => 'slugTransformado' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/categorias/edit.html.erb
<h1>Editar categoria</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', [:admin, @categoria] %> |
<%= link_to 'Voltar', admin_categorias_path %>

app/views/admin/categorias/index.html.erb
<h1>Lista de categorias</h1>
<div id="guardaListagens">
<table>
  <tr id="firstTr">
    <th>Nome</th>
    <th>Slug</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categorias.each do |categoria| %>
	<% if categoria == @categorias.last %>
		<tr class="ultimaTr">
	<% else %>
		<tr>
	<% end %>
    <td><%= "#{categoria.nome} (#{categoria.produtos.count})" %></td>
    <td><%= categoria.slug %></td>
    <td><%= link_to 'Mostrar', [:admin, categoria] %></td>
    <td><%= link_to 'Editar', edit_admin_categoria_path(categoria) %></td>
    <td><%= link_to 'Deletar', [:admin, categoria], confirm: 'Tem certeza que deseja excluir esta categoria?', method: :delete, :class => 'deletar' %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @categorias %>

<br />

<%= link_to 'Nova Categoria', new_admin_categoria_path, :id => 'novoItem' %>
</div>

app/views/admin/categorias/new.html.erb
<h1>Nova categoria</h1>

<%= render 'form' %>

<%= link_to 'Voltar', admin_categorias_path %>

app/views/admin/categorias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @categoria.nome %>
</p>

<p>
  <b>Slug:</b>
  <%= @categoria.slug %>
</p>


<%= link_to 'Editar', edit_admin_categoria_path(@categoria) %> |
<%= link_to 'Voltar', admin_categorias_path %>